### ISSUE TITLE
In IE 11, SCRIPT5007: Unable to get property 'get' of undefined or null reference

### ISSUE THREAD

**Issue by macwac** [browserify/node-util#40]
i've got this error in types.js on:

<pre><code>
  var TypedArrayProto_toStringTag =
      uncurryThis(
        Object.getOwnPropertyDescriptor(TypedArrayPrototype,
                                        Symbol.toStringTag).get);
</code></pre>

**Comment by ZhongQiangYe** [comment]
I got the same error with u

**Comment by goto-bus-stop** [comment]
We have a fallback for this code that's based on `Object.prototype.toString`, which is used in environments where `Symbol` is not available. It looks like we should also check that `TypedArrayPrototype[Symbol.toStringTag]` is available, and if not, use the `Object.prototype.toString` fallback instead.

**Comment by abhishekbhan** [comment]
So whats the solution for this now?

**Comment by amramamohanreddy** [comment]
I'm also facing this issue, when I moved from Angular 4.3 to Angular 7. Did anyone solve this issue? Appreciate if he/she share the solution.

**Comment by macwac** [comment]
@amramamohanreddy
@abhishekbhan 

Angular 8 here
In my case i must downgrade packgage (assert)[https://github.com/browserify/commonjs-assert] to 1.5 version

**Comment by pmcelreavy** [comment]
I'm getting the same issue in only one of our projects. We are not using "assert" so downgrading it won't help.

Is there a solution for this?

**Comment by ljharb** [comment]
toStringTags aren't robust anyways; i'd prefer to see browserify use a robust approach like https://npmjs.com/which-typed-array / https://npmjs.com/is-typed-array :-)
