### ISSUE TITLE
Checking of process.env

### ISSUE THREAD

**Issue by mariusrak** [browserify/node-util#48]
On a line [109](https://github.com/browserify/node-util/blob/master/util.js#L109) is a code `if (process.env.NODE_DEBUG) {` which apparently checks for node process environment variables. But when the code is imported in a browser, as it is intended, the `process` variable is not defined which causes error and premature finish of the code execution. This defies purpose of the package. Please repair the condition.

**Comment by ljharb** [comment]
Any working node bundler will automatically provide a `process.env` empty object; if it doesn't, it's broken.

**Comment by mariusrak** [comment]
I'm using webpack with node api, here's my config, is there anything wrong?
```javascript
webpack([{
    entry: path.resolve(/* a path */),
    output: {
      path: bundlePath,
      filename: "client.js"
    },
    module: {
      rules: [{
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            plugins: [
              "@babel/plugin-proposal-class-properties",
              "babel-plugin-dynamic-import-node",
            ],
            presets: [
              [
                "@babel/preset-env",
                {
                  targets: {
                    browsers: "> 0.25%, not dead",
                  },
                },
              ],
              "@babel/preset-react",
            ],
          },
        },
      }, ],
    },
    mode: "development",
    resolveLoader: {
      modules: [path.join( /* a path */ )],
    },
    resolve: {
      modules: [path.join( /* a path */ )],
      alias: {
        canny: path.resolve( /* a path */ ),
        modules: path.resolve( /* a path */ ),
      },
      extensions: ["*", ".js", ".jsx"],
    },
    plugins: [new HtmlWebpackPlugin()],
  },
  {
    /* Server configuration */
  },
]);
```

**Comment by ljharb** [comment]
Are you using webpack 5? If so, you have to explicitly handle it: https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed

**Comment by mariusrak** [comment]
Yes, I'm using webpack 5. Since this is polyfill itself, it could be done so it doesn't need any more polyfills. And also, webpack 5 would eventually become standard.

**Comment by ljharb** [comment]
The approach webpack 5 is taking makes it broken by design; follow that link’s instructions to unbreak it. L

This is a node module (as are most things on npm) and bundling node modules requires automatically shimming referenced node globals.
