### ISSUE TITLE
`process.env.NODE_DEBUG` is unsafe to use directly for browser

### ISSUE THREAD

**Issue by JounQin** [browserify/node-util#63]
https://github.com/browserify/node-util/blob/master/util.js#L109

`typeof process !== 'undefined'` should be checked like at https://github.com/browserify/node-util/blob/master/util.js#L76

**Comment by JounQin** [comment]
close in favor of #43

**Comment by ljharb** [comment]
The solution to webpack 5 being broken is here: https://github.com/browserify/node-util/issues/43#issuecomment-724353093
