### ISSUE TITLE
Content security policy error in node-util

### ISSUE THREAD

**Issue by shhnjk** [browserify/node-util#66]
Due to the use of [is-generator-function](https://github.com/inspect-js/is-generator-function/blob/63cd9353eead5ad5eb8cf581fc4129841641bb43/index.js#L13) in node-util, `script-src 'unsafe-eval'` CSP keyword is required to use node-util.

There had been discussions in https://github.com/inspect-js/is-generator-function/issues/41, and is-generator-function version 1.0.10 has an improvement of not calling `return Function("...")` unless it's necessary.

node-util should use is-generator-function version 1.0.10 to take that change in at least.

**Comment by ljharb** [comment]
It already does, because `^1.0.7` is a semver range that includes `1.0.10`. If you're stuck on an older version, that's your lockfile doing that, not this package.
