### ISSUE TITLE
How to promisify tmp-promise.file

### ISSUE THREAD

**Issue by jasonkhanlar** [browserify/node-util#70]
As stated in documentation at https://npmjs.com/package/tmp-promise

Asynchronous file creation
```
import { file } from 'tmp-promise'

(async () => {
  const {fd, path, cleanup} = await file();
  // work with file here in fd
  cleanup();
})(); 
```

but instead I used this code:

```
const tmpFile = util.promisify(require('tmp-promise').file);
console.log('output', await tmpFile()); // output /tmp/tmp-2113950-dGDocFSAEGpd
```

I was expecting to see the three values: fd, path, cleanup but the returned value is only a string. How can I simplify promisification whilst also having access to those other values? I don't think I can destroy the tempfile or remove the callback after I am finished working with it.

**Comment by ljharb** [comment]
Browserify is for making a browser bundle. In a browser, there's no filesystem available, so it doesn't make any sense at all for a temp file package to be used in a browser.

**Comment by jasonkhanlar** [comment]
Ah. I followed the link from https://npmjs.com/package/util and I see now that that project is different than https://nodejs.org/api/util.html

**Comment by ljharb** [comment]
The util package is meant to be a browser shim for node core’s util module. That doesn’t mean you can have temp files in the browser.
