### ISSUE TITLE
the name `fn` is defined multiple times when using `swc-loader`

### ISSUE THREAD

**Issue by achmadk** [browserify/node-util#75]
I have an ejected CRA with a custom webpack loader. I use `swc-loader` instead of `babel-loader` for faster compile time. Actually, I add `@walletconnect/web3-provider` into my app. I got an error to include `{ util: require.resolve('util/') }` into `resolve.fallback` webpack configuration. After that error was fixed, I got the error again like this

```sh
ERROR in ./node_modules/util/util.js
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: 
  × the name `fn` is defined multiple times
     ╭─[/media/data/SIDE_PROJECTS/webpack-react-ts-inversify-web-worker/node_modules/util/util.js:617:5]
 617 │ var fn = original[kCustomPromisifiedSymbol];
     ·     ─┬
     ·      ╰── previous definition of `fn` here
 618 │     if (typeof fn !== 'function') {
 619 │       throw new TypeError('The "util.promisify.custom" argument must be of type Function');
 620 │     }
 621 │     Object.defineProperty(fn, kCustomPromisifiedSymbol, {
 622 │       value: fn, enumerable: false, writable: false, configurable: true
 623 │     });
 624 │     return fn;
 625 │   }
 626 │ 
 627 │   function fn() {
     ·            ─┬
     ·             ╰── `fn` redefined here
     ╰────

```

could you please refactor the variable/function declaration name in order to solve my problem?

https://github.com/browserify/node-util/blob/a292d8a73ac877cc9a0ae64b287cc064dcbacb54/util.js#L617

https://github.com/browserify/node-util/blob/a292d8a73ac877cc9a0ae64b287cc064dcbacb54/util.js#L627

**Comment by ljharb** [comment]
No, this is valid sloppy mode code - swc must have a bug (perhaps, incorrectly defaulting CJS code to strict mode).

Browserify has no bug here.
