### ISSUE TITLE
i find a error about isBuffer function

### ISSUE THREAD

**Issue by wbhAvivahc** [browserify/node-util#76]
when i build use rollup, i find my project dist have a error about `exports.isBuffer = require('./support/isBuffer');`
my dist don't have this files (/support/isBuffer
![image](https://user-images.githubusercontent.com/27544066/176587287-cfeef295-4e01-4427-86ee-420defb8d6a2.png)
)

**Comment by ljharb** [comment]
That’s defined [here](https://github.com/browserify/node-util/blob/ad9dbe0df07655a38f0f8fc8feaeccb965d207e7/package.json#L10 ); seems like it’s a bug in rollup with the browser field.

**Comment by goto-bus-stop** [comment]
i think you may be missing the CommonJS plugin for rollup, as the `require` statement still exists in the output. This is a CommonJS module so you need to configure your bundler appropriately if it doesn't support CommonJS by default.
