### ISSUE TITLE
Reliance on `process.env.NODE_DEBUG`

### ISSUE THREAD

**Issue by JannikGM** [browserify/node-util#77]
This code will fail if `process` or `process.env` does not exist:

https://github.com/browserify/node-util/blob/6b828255a7f407efcd7e4d2c54ddb43256e491fb/util.js#L109-L110

We ran into this with vite.js 2.8.x which has another convention (https://vitejs.dev/guide/env-and-mode.html#env-variables).
node-util should probably have a safe fallback for when this environment variable does not exist (assume production build?).

We used a workaround described here: https://github.com/visgl/deck.gl/issues/6134#issuecomment-1201150859

**Comment by ljharb** [comment]
This is a node module; they always exist.

If vite doesn’t provide then, it’s not a node module bundler.

**Comment by JannikGM** [comment]
For people who see this in the future, there's also https://github.com/browserify/node-util/issues/43 which discusses this in more detail, and provides solutions for different tools which aren't node module bundlers.

**Comment by eddiemonge** [comment]
> This is a node module; they always exist.

That's not a good reason for not including a simple check like

```
if (process && process.env && process.env.NODE_DEBUG) {
```

Just because this may be a `node module` doesn't mean it will always run in node. Node alternatives are popping up that may want to use this to get node like things but may not expose process.

The README also states
> This implements the Node.js [util](https://nodejs.org/docs/latest-v8.x/api/util.html) module for environments that do not have it, like browsers.
which implies this is definitely not a node module.

**edit**
After reading #43, the issue is far deeper, but this one causes immediate breaking.

**Comment by ljharb** [comment]
Yes, it does mean that. An X module only ever runs in X, or in X-like environments.

**Comment by manzoorwanijk** [comment]
> This is a node module; they always exist.

@ljharb If it always exists, then may be we should remove these checks for `typeof process`?

https://github.com/browserify/node-util/blob/ef984721db7150f651800e051de4314c9517d42c/util.js#L76-L82

I don't understand the rigid behavior of denying to add a simple safety check. 🤷‍♂️ 

#62 should have been merged a long time ago. At least, it doesn't hurt or break anything.

**Comment by ljharb** [comment]
@manzoorwanijk true, we should remove those.

What it harms is that it furthers the tolerance of broken bundlers in the ecosystem.
