### ISSUE TITLE
show a deprecation warning on when using `util.inherit`

### ISSUE THREAD

**Issue by jimmywarting** [browserify/node-util#78]
b/c inherit is discouraged could you give the ppl a warning for using it so ppl will update?

> Usage of util.inherits() is discouraged. Please use the ES6 class and extends keywords to get language level inheritance support. [@nodejs](https://nodejs.org/dist/latest-v18.x/docs/api/util.html#utilinheritsconstructor-superconstructor)

**Comment by ljharb** [comment]
In what node version was this warning added?

(either way, node-based tests should be emitting this warning regardless)

**Comment by goto-bus-stop** [comment]
It's not deprecated, just legacy. a runtime warning would be far too invasive (node.js also doesn't have one).
